available()
{
	which "$1" >/dev/null 2>&1
}

niceinfo() {
cat <<EOF
>>
>> WARNING THIS CAN LEAD TO DATA LOSS
>> 
>> For people who want to use the same profile for opera-devel
>> as they use for opera, start opera-devel as follows:
>>
>> # opera-devel -pd ~/.opera
>>
>> You can make this more permenant by editing 
>> /usr/bin/opera-devel and setting 
>> \$OPERA_PERSONALDIR to \$HOME/.opera
>>
>> WARNING THIS CAN LEAD TO DATA LOSS
>> 
EOF
}

updatemimeandall() {

	if available update-desktop-database
	then
		update-desktop-database -q /usr/share/applications
	fi

	if available update-mime-database
	then
		update-mime-database /usr/share/mime >/dev/null
	fi

	touch -c usr/share/icons/hicolor
	if available update-icon-caches
	then
		update-icon-caches -tq /usr/share/icons/hicolor
	elif available gtk-update-icon-cache
	then
		gtk-update-icon-cache -tq /usr/share/icons/hicolor
	fi

}

post_install() {
	niceinfo
	updatemimeandall
}

post_upgrade() {
	niceinfo
	updatemimeandall
}

post_remove() {
	updatemimeandall
}
