available()
{
	which "$1" >/dev/null 2>&1
}

niceinfo() {
	echo ">>"
	echo ">> WARNING THIS CAN LEAD TO DATA LOSS"
	echo ">>"
	echo ">> For people who want to use the same profile for opera-devel"
	echo ">> start opera-devel with the following commandline"
	echo ">>"
	echo ">> # opera-devel -pd ~/.opera"
	echo ">>"
	echo ">> WARNING THIS CAN LEAD TO DATA LOSS"
	echo ">>"
}

updatemimeandall() {
	if available update-mime-database
	then
		update-mime-database /usr/share/mime >/dev/null
	fi

	if available update-desktop-database
	then
		update-desktop-database -q /usr/share/applications
	fi

	if available gtk-update-icon-cache
	then
		gtk-update-icon-cache -q /usr/share/icons/hicolor
	fi
}

post_install() {
	niceinfo
	updatemimeandall
}

post_upgrade() {
	niceinfo
	updatemimeandall
}

post_remove() {
	updatemimeandall
}
