#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/vbox/vbox.cfg

MODLIST=('vboxdrv' 'vboxnetadp' 'vboxnetflt')
LOG="/var/log/vbox-install.log"

if [ -n "$INSTALL_DIR" ]; then
  VBOXMANAGE="$INSTALL_DIR/VBoxManage"
  BUILDVBOXDRV="$INSTALL_DIR/src/vboxhost/vboxdrv/build_in_tmp"
  BUILDVBOXNETFLT="$INSTALL_DIR/src/vboxhost/vboxnetflt/build_in_tmp"
  BUILDVBOXNETADP="$INSTALL_DIR/src/vboxhost/vboxnetadp/build_in_tmp"
else
  echo "missing vbox.cfg"
  exit 0
fi

case "$1" in
  start)
    stat_busy "Loading VirtualBox kernel modules"
    returnval=0
    for module in ${MODLIST[@]}; do
      modprobe $module > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        returnval=1
      fi
    done
    if [ $returnval -ne 0 ]; then
      $0 build
      $0 start
    fi
    stat_done
    ;;
  stop)
    stat_busy "Unloading VirtualBox kernel modules"
    let md=${#MODLIST[@]}-1
    while [ $md -ge 0 ]; do
      if grep -q "^${MODLIST[$md]#@}" /proc/modules; then
        modprobe -r ${MODLIST[$md]#@}
      fi
      let md=md-1
    done
    stat_done
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  setup)
    $0 stop
    $0 build
    $0 start
    ;;
  build)
    for p in /lib/modules/*; do
      if [ ! -d "$p/kernel" ]; then
        if [ -e "$p/misc/vboxdrv.ko" ]; then
          stat_busy "Removing old VirtualBox kernel modules from $p"
          rm -f "$p/misc/vbox"{drv,netadp,netflt}.ko 2>/dev/null
          rmdir -p --ignore-fail-on-non-empty "$p/misc/" 2>/dev/null
          stat_done
        fi
      fi
    done
    if find /lib/modules/`uname -r` -name "vboxnetadp\.*" 2>/dev/null|grep -q vboxnetadp; then
      stat_busy "Removing old VirtualBox netadp kernel module"
      find /lib/modules/`uname -r` -name "vboxnetadp\.*" 2>/dev/null|xargs rm -f 2>/dev/null
      stat_done
    fi
    if find /lib/modules/`uname -r` -name "vboxnetflt\.*" 2>/dev/null|grep -q vboxnetflt; then
      stat_busy "Removing old VirtualBox netflt kernel module"
      find /lib/modules/`uname -r` -name "vboxnetflt\.*" 2>/dev/null|xargs rm -f 2>/dev/null
      stat_done
    fi
    if find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|grep -q vboxdrv; then
      stat_busy "Removing old VirtualBox kernel module"
      find /lib/modules/`uname -r` -name "vboxdrv\.*" 2>/dev/null|xargs rm -f 2>/dev/null
      stat_done
    fi
    stat_busy "Recompiling VirtualBox kernel modules"
    if ! $BUILDVBOXDRV \
      --save-module-symvers /tmp/vboxdrv-Module.symvers \
      --no-print-directory install > $LOG 2>&1; then
      echo  "Look at $LOG to find out what went wrong"
    fi
    if ! $BUILDVBOXNETFLT \
      --use-module-symvers /tmp/vboxdrv-Module.symvers \
      --no-print-directory install >> $LOG 2>&1; then
      echo "Look at $LOG to find out what went wrong"
    fi
    if ! $BUILDVBOXNETADP \
      --use-module-symvers /tmp/vboxdrv-Module.symvers \
      --no-print-directory install >> $LOG 2>&1; then
      echo "Look at $LOG to find out what went wrong"
    fi
    stat_done
    ;;
  *)
    echo "usage: $0 {start|stop|restart|setup}"
esac
