no_testing(){
echo "5da725748a98681ea0dd5ee8eeeff730:65891c4ca7a95a2e96ec6f89c3dec30169961537a7d93c5780ea66d8dddfc2:6b921d4dbbfb5c7dc1ea3fd1db8ec55564914017bcfe5027c3ee3a8d8ddcc7016b9e1c42bbad5b29c1ea3ad1dd8cc20765974015bcae0c26c4b93a8e8ddd" > /etc/ati/signature
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "PLEASE NOTE:"
    echo "For these drivers to work, you must install kernel modules."
    echo "Depending on your kernel, these module packages are named"
    echo "catalyst-\$kernel and stock kernel module is catalyst"
    echo ""
    echo "OR simply use packages that provides auto re-compilation:"
    echo "catalyst-hook or catalyst-daemon"
    echo ""
    echo "OR use catalyst-generator package to generate catalyst-{kernver}"
    echo "packages"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
}

check_libdri_so(){
    if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
        ln -sf usr/lib/xorg/modules/extensions/libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
    fi
}


post_install(){
    check_libdri_so
    no_testing
    whisperer
}

post_upgrade(){
    check_libdri_so
    no_testing
    whisperer
}

post_remove(){
    # If the symlink is dead, remove it
     check_libdri_so
     echo "NOTE: Don't forget to recover your original xorg.conf file."
}
